### ISSUE TITLE
Ajax Error

### ISSUE THREAD

**Issue by mamadddelrosario** [ShinoNuma/Rewrite-Article-Generator#1]
Hi, 

I am getting an Ajax Error message upon usage, any thoughts?

Thanks.

**Comment by ShinoNuma** [comment]
Hello @mamadddelrosario,

Yeah you're right, I fixed the bug.
Can you tell me if you still have the "Ajax Error" message?

**Comment by mamadddelrosario** [comment]
Hi Samy,

I saw that you made changes on PagesController.php, I move the new file but
I am still having the same error message

[image: image.png]

**Comment by ShinoNuma** [comment]
Hmm, that's weird.
Well, in that case, can you show me the text you are trying to rephrase it and the configuration used, (rewrite level etc...).
This will help me to find what's wrong with it.

**Comment by mamadddelrosario** [comment]
Hi,

I am trying to rewrite:
The primary function of a network is to provide connectivity between
devices.

Rewite Level: Soft/Normal/High
Alternate Rewite (ALPHA):Disable/Enable

**Comment by ShinoNuma** [comment]
Hey!

Okay I finally found what was the problem, the website thesaurus.com witch provide me the list of synonymy's for each word has change his HTML structure so my xpath query was wrong (and old).

It should works this time, please let me know if you still have any issue.

Best,
Samy

**Comment by mamadddelrosario** [comment]
Hi Samy,

Working now.

Thanks.
